version: '3'  
services:  
  nodeapp:  
    image: node_sinar_hr
    restart: always  
    command: forever start /usr/src/app/index.js  
    volumes:  
      - .:/usr/src/app  
    working_dir: /usr/src/app  