from sqlalchemy import Column, Integer, Float, String, Date, LargeBinary
from app.database import Base

class Employee(Base):
    __tablename__ = 'm_employee'
    employee_id = Column(Integer, primary_key=True, index=True)
    
    fingerid = Column(String(255))
    nip = Column(String(255))
    name = Column(String(255))
    company_id = Column(Integer)
    department_id = Column(Integer)
    position_id = Column(Integer)
    employeestatus_id = Column(Integer)
    bank_id = Column(Integer)
    bankaccountnumber = Column(String(255))
    bankaccountname = Column(String(255))
    username = Column(String(255))
    password = Column(String(255))
    email = Column(String(255))
    hp = Column(String(255))
    joindate = Column(Date)
    worklength = Column(Float)
    status = Column(String(255))
    jamsostek_id = Column(Integer)
    no_bpjstk = Column(String(255))
    no_bpjsks = Column(String(255))
    ptkp = Column(String(255))
    taxtype = Column(Integer)
    taxirregular = Column(Integer)
    taxfinal = Column(Integer)
    sex = Column(String(255))
    pob = Column(String(255))
    dob	 = Column(Date)

    age = Column(Float)
    agama = Column(String(255))
    married = Column(String(255))
    npwp = Column(String(255))
    address = Column(String(255))
    idtype = Column(String(255))
    idnumber = Column(String(255))
    photo = Column(LargeBinary) 
    resigndate	 = Column(Date)
    resigntype_id = Column(Integer)
    resign_reason = Column(String(255))
    status_active = Column(Integer)

    useradded = Column(String(255))
    dateadded = Column(Date)
    useredited = Column(String(50))
    dateedited = Column(Date)